### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by cescvietnam** [iot-lnu/applied-iot#6]
When I run command "docker-compose up", the following error occurred:
"ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/"

Do you have any idea what's the issue and how to fix it?

**Comment by frahlg** [comment]
This repository has not been updated for a while, check this out instead: https://github.com/iot-lnu/tig-stack which is recently updated. I will remove this one.
